codes/urls.py
from django.urls import path, include
from . import views

app_name="codes"
urlpatterns = [
    path('', views.GetDashboard, name='dashboard'),
    path('met-stations/', views.GetStations, name="get_stations"),
    path('synops/', views.GetSynops, name="get_synops"),
    path('data-exporting/', views.GetDataExporting, name="data_exporting"),
    path('api/data/', include('codes.api.urls'))

    # web apis
    # path('all-stations/', GetStations.as_view()),
    # path('station/<station_id>/', GetSingleStation.as_view()),
    # path('today-codes/',TodayCodes.as_view()),
    # path('codes/<synop_id>/', GetSingleCode.as_view()),
]

synopBackendv2/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('user_account.urls')),
    path('dashboard/', include('codes.urls'))
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

user_account/urls.py
from django.urls import path, include
from . import views

app_name="accounts"
urlpatterns = [
    path('', views.getHome, name="login"),
    path('logout', views.logoutUser, name="logout"),
    path('api/user/', include('user_account.api.urls')),

    # path
    path('stations/new/', views.CreateStation.as_view(), name="new_station"),
    path('observers/list/', views.GetObservers, name="get_observers"),
    path('observer/new/', views.NewObservers, name="new_observer"),
    path('observer/<userId>/delete/', views.RemoveObserver, name="Remove_observer"),
    path('reassign-observer/<userID>/', views.ReassignObserver, name="reasssign_observer"),
    path('single-station/<stationId>/', views.GetSingleStation, name="single_station"),
    path('station/<stationId>/edit/', views.EditStation, name="edit_station"),
    path('station/<stationId>/delete/', views.DeleteStation, name="delete_station")
]

templates/partials/filter_data.html
<form action="" method="post" class="">
    {% csrf_token %}
    <div class="grid grid-cols-1 place-items-center">
        <div date-rangepicker class="flex items-center">
            <div class="relative">
                <div class="absolute inset-y-0 left-0 flex items-center pl-3 pointer-events-none">
                    <svg aria-hidden="true" class="w-5 h-5 text-gray-500 dark:text-gray-400" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" d="M6 2a1 1 0 00-1 1v1H4a2 2 0 00-2 2v10a2 2 0 002 2h12a2 2 0 002-2V6a2 2 0 00-2-2h-1V3a1 1 0 10-2 0v1H7V3a1 1 0 00-1-1zm0 5a1 1 0 000 2h8a1 1 0 100-2H6z" clip-rule="evenodd"></path></svg>
                </div>
                <input name="start" datepicker-format="mm/dd/yyyy"  type="text" class="bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full pl-10 p-2.5  dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500" placeholder="Select date start" required>
            </div>
            <span class="mx-4 text-gray-500">to</span>
            <div class="relative">
                <div class="absolute inset-y-0 left-0 flex items-center pl-3 pointer-events-none">
                    <svg aria-hidden="true" class="w-5 h-5 text-gray-500 dark:text-gray-400" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" d="M6 2a1 1 0 00-1 1v1H4a2 2 0 00-2 2v10a2 2 0 002 2h12a2 2 0 002-2V6a2 2 0 00-2-2h-1V3a1 1 0 10-2 0v1H7V3a1 1 0 00-1-1zm0 5a1 1 0 000 2h8a1 1 0 100-2H6z" clip-rule="evenodd"></path></svg>
                </div>
                <input name="end" datepicker-format="mm/dd/yyyy"  type="text" class="bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full pl-10 p-2.5  dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500" placeholder="Select date end" required>
            </div>
            <div class="relative">
           

        </div>
        <div class="ml-4">
             <select name="station" id="" class="w-full rounded-lg h-10 px-4 py-2 focus:outline-none" required>
                <option value="" disabled selected>Select your Weather station</option>
                {% for station in stations %}
                <option value="{{station.station_number}}">{{station.station_name}}</option>
                {% endfor %}
             </select>
        </div>
        <div class="ml-4">
            <select name="parameter" id="" class="w-full rounded-lg h-10 px-4 py-2 focus:outline-none" required>
               <option value="" disabled selected>Weather Parameter</option>
               <option value="dry_bulb">Temperature</option>
               <option value="rainfall_amount">Rainfall</option>
               <!-- <option value="wind_speed">Wind</option> -->
            </select>
       </div>
    </div>
    <button type="submit" class="px-5 py-1.5 bg-blue-500 shadow-lg rounded-lg mt-6 text-white font-bold">Submit</button>

    </div>
    
</form>

templates/partials/header.html
<div class="sticky z-10 top-0 h-16 border-b bg-white lg:py-2.5">
    <div class="px-6 flex items-center justify-between space-x-4 2xl:container">
        <h5 hidden class="text-2xl text-gray-600 font-medium lg:block"></h5>
        <button class="w-12 h-16 -mr-2 border-r lg:hidden">
            <svg xmlns="http://www.w3.org/2000/svg" class="h-6 w-6 my-auto" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M4 6h16M4 12h16M4 18h16" />
            </svg>
        </button>
        <div class="flex space-x-4">
            <!--search bar -->
            <div hidden class="md:block">
                <div class="relative flex items-center text-gray-400 focus-within:text-cyan-400">
                    <span class="absolute left-4 h-6 flex items-center pr-3 border-r border-gray-300">
                    <svg xmlns="http://ww50w3.org/2000/svg" class="w-4 fill-current" viewBox="0 0 35.997 36.004">
                        <path id="Icon_awesome-search" data-name="search" d="M35.508,31.127l-7.01-7.01a1.686,1.686,0,0,0-1.2-.492H26.156a14.618,14.618,0,1,0-2.531,2.531V27.3a1.686,1.686,0,0,0,.492,1.2l7.01,7.01a1.681,1.681,0,0,0,2.384,0l1.99-1.99a1.7,1.7,0,0,0,.007-2.391Zm-20.883-7.5a9,9,0,1,1,9-9A8.995,8.995,0,0,1,14.625,23.625Z"></path>
                    </svg>
                    </span>
                    <input type="search" name="leadingIcon" id="leadingIcon" placeholder="Search here" class="w-full pl-14 pr-4 py-2.5 rounded-xl text-sm text-gray-600 outline-none border border-gray-300 focus:border-cyan-300 transition">
                </div>
            </div>
            <!--/search bar -->
            <button aria-label="search" class="w-10 h-10 rounded-xl border bg-gray-100 focus:bg-gray-100 active:bg-gray-200 md:hidden">
                <svg xmlns="http://ww50w3.org/2000/svg" class="w-4 mx-auto fill-current text-gray-600" viewBox="0 0 35.997 36.004">
                    <path id="Icon_awesome-search" data-name="search" d="M35.508,31.127l-7.01-7.01a1.686,1.686,0,0,0-1.2-.492H26.156a14.618,14.618,0,1,0-2.531,2.531V27.3a1.686,1.686,0,0,0,.492,1.2l7.01,7.01a1.681,1.681,0,0,0,2.384,0l1.99-1.99a1.7,1.7,0,0,0,.007-2.391Zm-20.883-7.5a9,9,0,1,1,9-9A8.995,8.995,0,0,1,14.625,23.625Z"></path>
                </svg>
            </button>

            <p class="mt-2">{% if user.is_authenticated  %} Hi, {{user.email}}  {% endif %}</p>
        </div>
    </div>
 </div>
 

templates/partials/sidebar.html
<aside  id="sidebar" class="ml-[-100%] fixed z-10 top-0 pb-3 px-6 w-full flex flex-col justify-between h-screen border-r bg-white transition duration-300 md:w-4/12 lg:ml-0 lg:w-[25%] xl:w-[20%] 2xl:w-[15%]">
    <div>
        <div class="-mx-6 px-6 py-4">
            <a href="#" title="home" class="flex">
                <!-- <img src="../../../../assets/ecast.png" class="w-10" alt="ecast log"> -->
                <p class="font-bold text-gray-700 mt-2 ml-2 text-xl text-center">SYNOP</p>
            </a>
        </div>
  
        <div class="mt-8 text-center">
            <!-- <img src="../../../../assets/user.png" alt="" class="w-10 h-10 m-auto rounded-full object-cover lg:w-28 lg:h-28"> -->
            <h5 class="hidden mt-4 text-xl font-semibold text-gray-600 lg:block">{{username}}</h5>
        </div>
  
        <ul class="space-y-2 tracking-wide mt-8">
            <li>
                <a href="{% url 'codes:dashboard' %}" aria-label="dashboard" class="relative px-4 py-3 flex items-center space-x-4 rounded-xl">
                   <img src="/static/images/dashboard.png" class="w-5 h-5" alt="">
                    <span class="-mr-1 font-medium">Overview</span>
                </a>
            </li>
            <li>
                <a href="{% url 'codes:get_stations' %}" class="px-4 py-3 flex items-center space-x-4 rounded-md text-gray-600 group">
                   <img src="/static/images/climatology.png" class="w-5 h-5" alt="">
                    <span class="-mr-1 font-medium">Met Stations</span>
                </a>
            </li>
            <li>
                <a href="{% url 'codes:get_synops' %}" class="px-4 py-3 flex items-center space-x-4 rounded-md text-gray-600 group">
                   <img src="/static/images/monitor.png" class="w-5 h-5" alt="">
                    <span class="-mr-1 font-medium">Synops</span>
                </a>
            </li>
            <li>
                <a href="{% url 'accounts:get_observers' %}" class="px-4 py-3 flex items-center space-x-4 rounded-md text-gray-600 group">
                   <img src="/static/images/user.png" class="w-5 h-5" alt="">
                    <span class="-mr-1 font-medium">Users</span>
                </a>
            </li>
            <li>
                <a href="{% url 'codes:data_exporting' %}" class="px-4 py-3 flex items-center space-x-4 rounded-md text-gray-600 group">
                   <img src="/static/images/data.png" class="w-5 h-5" alt="">
                    <span class="-mr-1 font-medium">Date Exporting</span>
                </a>
            </li>
        </ul>
    </div>
  
    <div class="px-6 -mx-6 pt-4 flex justify-between items-center border-t">
        <a href="{% url 'accounts:logout' %} " class="px-4 py-3 flex items-center space-x-4 rounded-md text-gray-600 group">
            <svg xmlns="http://www.w3.org/2000/svg" class="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M17 16l4-4m0 0l-4-4m4 4H7m6 4v1a3 3 0 01-3 3H6a3 3 0 01-3-3V7a3 3 0 013-3h4a3 3 0 013 3v1" />
            </svg>
            <span class="group-hover:text-gray-700">Logout</span>
        </a>
    </div>
  </aside>