codes/urls.py
from django.urls import path, include
from . import views

app_name="codes"
urlpatterns = [
    path('', views.GetDashboard, name='dashboard'),
    path('met-stations/', views.GetStations, name="get_stations"),
    path('synops/', views.GetSynops, name="get_synops"),
    path('data-exporting/', views.GetDataExporting, name="data_exporting"),
    path('api/data/', include('codes.api.urls'))

    # web apis
    # path('all-stations/', GetStations.as_view()),
    # path('station/<station_id>/', GetSingleStation.as_view()),
    # path('today-codes/',TodayCodes.as_view()),
    # path('codes/<synop_id>/', GetSingleCode.as_view()),
]

synopBackendv2/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('user_account.urls')),
    path('dashboard/', include('codes.urls'))
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

user_account/urls.py
from django.urls import path, include
from . import views

app_name="accounts"
urlpatterns = [
    path('', views.getHome, name="login"),
    path('logout', views.logoutUser, name="logout"),
    path('api/user/', include('user_account.api.urls')),

    # path
    path('stations/new/', views.CreateStation.as_view(), name="new_station"),
    path('observers/list/', views.GetObservers, name="get_observers"),
    path('observer/new/', views.NewObservers, name="new_observer"),
    path('observer/<userId>/delete/', views.RemoveObserver, name="Remove_observer"),
    path('reassign-observer/<userID>/', views.ReassignObserver, name="reasssign_observer"),
    path('single-station/<stationId>/', views.GetSingleStation, name="single_station"),
    path('station/<stationId>/edit/', views.EditStation, name="edit_station"),
    path('station/<stationId>/delete/', views.DeleteStation, name="delete_station")
]

templates/dashboard/assign.html
{% extends 'base.html' %}
{% load tailwind_filters %}
{% block content %}
<div class="p-8">
    <!-- page headers -->
    <div class="flex justify-between">
        <h1 class="font-bold text-gray-800 text-2xl">Reassign Observer</h1>
    </div>
    <!-- form -->
    <div class="mt-8">
        <form action="" method="post">
            {% csrf_token %}
            <div>
                {{ form|crispy }}
                <input type="submit" style="background-color:#3272e9" value="Re-assign" class=" mb-2 text-white focus:ring-4 focus:outline-none focus:ring-blue-300 font-medium rounded-lg text-sm w-1/2  sm:w-auto px-5 py-2.5 text-center dark:focus:ring-blue-800">
            </div>
        </form>
    </div>
</div>

{% endblock %}

templates/dashboard/data_exporting.html
{% extends 'base.html' %}
{% block content %}
<div class="p-8">
    <!-- page header starts here -->
    <div>
        <h1 class="font-bold text-gray-800 text-2xl">Data Exportation</h1>
        <p class="text-sm text-grey-500">Create a range of your dataset</p>
    </div>
    <!-- page header ends here -->

    <!-- page content  start here-->
    <div class="mt-8 flex justify-between">
        <!--date picker -->
        <form action="" method="post" class="">
            {% csrf_token %}
            <div class="grid grid-cols-1 place-items-center">
                <div date-rangepicker class="flex items-center">
                    <div class="relative">
                        <div class="absolute inset-y-0 left-0 flex items-center pl-3 pointer-events-none">
                            <svg aria-hidden="true" class="w-5 h-5 text-gray-500 dark:text-gray-400" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" d="M6 2a1 1 0 00-1 1v1H4a2 2 0 00-2 2v10a2 2 0 002 2h12a2 2 0 002-2V6a2 2 0 00-2-2h-1V3a1 1 0 10-2 0v1H7V3a1 1 0 00-1-1zm0 5a1 1 0 000 2h8a1 1 0 100-2H6z" clip-rule="evenodd"></path></svg>
                        </div>
                        <input name="start" datepicker-format="mm/dd/yyyy"  type="text" class="bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full pl-10 p-2.5  dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500" placeholder="Select date start" required>
                    </div>
                    <span class="mx-4 text-gray-500">to</span>
                    <div class="relative">
                        <div class="absolute inset-y-0 left-0 flex items-center pl-3 pointer-events-none">
                            <svg aria-hidden="true" class="w-5 h-5 text-gray-500 dark:text-gray-400" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" d="M6 2a1 1 0 00-1 1v1H4a2 2 0 00-2 2v10a2 2 0 002 2h12a2 2 0 002-2V6a2 2 0 00-2-2h-1V3a1 1 0 10-2 0v1H7V3a1 1 0 00-1-1zm0 5a1 1 0 000 2h8a1 1 0 100-2H6z" clip-rule="evenodd"></path></svg>
                        </div>
                        <input name="end" datepicker-format="mm/dd/yyyy"  type="text" class="bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full pl-10 p-2.5  dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500" placeholder="Select date end" required>
                    </div>
                    <div class="relative">
                   
    
                </div>
                <div class="ml-4">
                     <select name="station" id="" class="w-full rounded-lg h-10 px-4 py-2 focus:outline-none" required>
                        <option value="" disabled selected>Select your Weather station</option>
                        {% for station in stations %}
                        <option value="{{station.station_number}}">{{station.station_name}}</option>
                        {% endfor %}
                     </select>
                </div>
                <div class="ml-4">
                    <select name="parameter" id="" class="w-full rounded-lg h-10 px-4 py-2 focus:outline-none" required>
                       <option value="" disabled selected>Weather Parameter</option>
                       <option value="dry_bulb">Temperature</option>
                       <option value="rainfall_amount">Rainfall</option>
                       <!-- <option value="wind_speed">Wind</option> -->
                    </select>
               </div>
            </div>
            <button type="submit" class="px-5 py-1.5 bg-blue-500 shadow-lg rounded-lg mt-6 text-white font-bold">Submit</button>

            </div>
            
        </form>
    </div>
</div>
{% endblock %}

templates/dashboard/edit_station.html
{% extends 'base.html' %}
{% load tailwind_filters %}
{% block content %}
<div class="p-8">
    <h1 class="font-bold text-gray-800 text-2xl">Edit Station</h1>
    <div class="mt-8">
       <form action="" method="post">
        {% csrf_token %}
        <div>
            {{ form|crispy }}
            <input type="submit" style="background-color:#3272e9" value="Edit Station" class=" mb-2 text-white focus:ring-4 focus:outline-none focus:ring-blue-300 font-medium rounded-lg text-sm w-1/2  sm:w-auto px-5 py-2.5 text-center dark:focus:ring-blue-800">
        </div>
       </form>
    </div>
</div>
{% endblock %}

templates/dashboard/index.html
{% extends 'base.html' %}

{% block content %}
<div class="p-8">
    <h1 class="font-bold text-gray-800 text-2xl">Overview</h1>
    <!-- latest data view -->
    <div class="mt-8">
        <!-- latest synops -->
        {% if synops %}
        <div>
            <!-- lastest synop data summaries -->
            <div class="grid grid-cols-3 gap-4">
                {% for synop in synops %}
                <div class="bg-white-500 shadow-lg rounded-lg px-4 py-2">
                    <!-- header -->
                    <h1 class="text-bold">{{synop.data.station_id}}</h1>
                    <div class="mt-2">
                        <p>{{synop.code}}</p>
                    </div>
                </div>
                {% endfor %}
            </div>
        </div>
        {% else %}
        <div class="mt-8">
            <p class="text-center">No Activity Today</p>
        </div>
        {% endif %}

        
    </div>

</div>
    <!-- <div id="main" class="">
        <div class="grid grid-cols-1 gap-4 md:grid-cols-2 lg:grid-cols-3">
            {% for synop in synops %}
            <div class="shadow-xl rounded-lg px-2 py-1 bg-white-500 mt-4">
                <div>
                    <p class="text-bule-700 font-bold text-lg">
                  {{data.station_id}}
                    </p>
                </div>
                <div>
                   <p class="text-xl my-2">{{code}}</p>
                </div>
                <div>
                   <p>{{created}}</p>
                </div>
            </div>
            {% endfor %}
            askjdhad
        </div>
    </div> -->

{% endblock %}

templates/dashboard/new_observer.html
{% extends 'base.html' %}
{% block content %}
<div class="p-8">
    <!-- page headers -->
    <div class="flex justify-between">
        <h1 class="font-bold text-gray-800 text-2xl">New User</h1>
        <!-- <a href="{% url 'accounts:new_station'  %}" style="background-color:#EF68F3" class="font-medium text-white px-4 py-2 rounded-lg shadow-lg">New Observer</a> -->
    </div>

    <!-- form -->
    <div class="mt-8">
        <form action="" method="post">
            {% csrf_token %}
            <div class="mb-6">
                <label for="email" class="block mb-2 text-sm font-medium font-bold text-black">Email</label>
               <input type="email" name="email" class=" border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5  dark:border-gray-600 dark:placeholder-gray-400 dark:focus:ring-blue-500 dark:focus:border-blue-500" placeholder="email address" required>
            </div>
            <div class="mb-6">
                <label for="email" class="block mb-2 text-sm font-medium font-bold text-black">Name</label>
               <input type="text" name="name" class=" border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5  dark:border-gray-600 dark:placeholder-gray-400 dark:focus:ring-blue-500 dark:focus:border-blue-500" placeholder="Observer's Name" required>
            </div>
            <div class="mb-6">
                <label for="station" class="block mb-2 text-sm font-medium rounded-lg font-bold text-black">Station</label>
                 <select name="station" class="w-full h-9 py-2 " required>
                    {% for station in stations %}
                    <option value="{{station.station_number}}">{{station.station_name}}</option>
                    {% endfor %}
                 </select>
              </div>
              <div class="mb-6">
               <div class="flex">
                <div>
                    <input type="checkbox" name="is_staff" value="1">
                    <label for="">Is Staff</label>
                </div>
<!--                <div class="ml-8">-->
<!--                    <input type="checkbox" name="is_admin" id="">-->
<!--                    <label for="">Is Admin</label>-->
<!--                </div>-->
               </div>
            </div>
            <div class="mb-6">
                <input type="submit" value="Create User" class="bg-blue-500 text-white px-4 py-2 shadow-lg rounded-lg font-bold">
            </div>
        </form>
    </div>
</div>
{% endblock %}

templates/dashboard/new_station.html
{% extends 'base.html' %}
{% load tailwind_filters %}
{% block content %}
<div class="p-8">
    <h1 class="font-bold text-gray-800 text-2xl">New Station</h1>
    <div class="mt-8">
       <form action="" method="post">
        {% csrf_token %}
        <div>
            {{ form|crispy }}
            <input type="submit" style="background-color:#3272e9" value="Add Station" class=" mb-2 text-white focus:ring-4 focus:outline-none focus:ring-blue-300 font-medium rounded-lg text-sm w-1/2  sm:w-auto px-5 py-2.5 text-center dark:focus:ring-blue-800">
        </div>
       </form>
    </div>
</div>
{% endblock %}

templates/dashboard/observers.html
{% extends 'base.html' %}
{% block content %}
<div class="p-8">
    <!-- page headers -->
    <div class="flex justify-between">
        <h1 class="font-bold text-gray-800 text-2xl">Observers</h1>
        <a href="{% url 'accounts:new_observer'  %}" style="background-color:#EF68F3" class="font-medium text-white px-4 py-2 rounded-lg shadow-lg">New Observer</a>
    </div>

    <!-- content -->
    <div class="mt-8">
        {% if observers %}
        <div>
            <div class="grid grid-cols-4 gap-4">
                {% for observer in observers %}
                <div class="bg-white-500 shadow-lg rounded-lg p-4">
                    <!-- images -->
                    <div class="flex justify-between">
                        <div>
                            <img src="/static/images/user.png" class="w-28" alt="">
                    <!-- info -->
                    <div class="mt-2">
                        <p class="font-medium text-md">{{observer.name}}</p>
                        <p class="text-sm text-gray-700">{{observer.station}}</p>
                    </div>
                        </div>
                        <!-- button -->
                        <div class="flex flex-col justify-center align-center">
                            <a href="{% url 'accounts:reasssign_observer' observer.id %}" class="bg-blue-600 text-white text-center my-2 rounded-lg shadow-lg px-2 py-1.5"><i class="fa-solid fa-pen-to-square"></i> Reassign</a>
                            <a href="{% url 'accounts:Remove_observer' observer.id %}" class="bg-red-600 text-white text-center my-2 rounded-lg shadow-lg px-2 py-1.5">                                <i class="fa-solid fa-trash"></i>
                                Remove</a>
                        </div>
                    </div>
                </div>
                {% endfor %}
            </div>
        </div>
        {% else %}
        {% endif %}
    </div>
</div>
{% endblock %}

templates/dashboard/station_details.html
{% extends 'base.html' %}
{% block content %}
<div class="p-8">
    <!-- page headers -->
    <div class="flex justify-between">

        <h1 class="font-bold text-gray-800 text-2xl flex">{{station.station_name}} <p class="font-normal mx-2"> - </p>  <p class="font-normal">{{station.district}}</p></h1> 
        <div class="flex">
            <a href="{% url 'accounts:edit_station' station.id %}" class="px-5 py-1.5 bg-blue-500 font-bold text-white shadow-lg rounded-lg mr-4">Edit</a>
            <form action="{% url 'accounts:delete_station' station.id %}" method="post">
                {% csrf_token %}
                <button type="submit" class="px-5 py-1.5 bg-red-500 font-bold text-white shadow-lg rounded-lg">Delete</button>
            </form>
        </div>
    </div>

    <!-- page content -->
    <div class="">
        <!-- subtext -->
        <div class="mt-2">
            {% if user %}
                {% for user in user %}
                <p class="text-sm">Under {{user.name}} leadership</p>
                {% endfor %}
            {% else %}
                <p>No Observer assigned</p>
            {% endif %}
        </div>

        <!-- data -->
        <div class="mt-8">
            <h1 class="font-medium text-lg">Synops</h1>
            <div class="my-2">
               {% if synops %}
                {% for synop in synops %}
                {% endfor %}
               {% else %}
                 <p class="text-center">No synops available</p>
               {% endif %}
            </div>
        </div>
    </div>
</div>
{% endblock %}

{% block script %}
<script>

</script>
{% endblock %}

templates/dashboard/stations.html
{% extends "base.html" %} 
{% block content %}
<div class="p-8">
    <!-- page header -->
    <div class="flex justify-between">
        <h1 class="font-bold text-gray-800 text-2xl">Weather Stations</h1>
        <a href="{% url 'accounts:new_station'  %}" style="background-color:#EF68F3" class="font-medium text-white px-4 py-2 rounded-lg shadow-lg">New Station</a>
    </div>

    <!-- page body -->
    <div class="mt-8">
        {% if stations %}
        <div>
            <!-- display station card -->
           <div class="grid grid-cols-4 gap-4 place-items-center">
            {% for station in stations %}
               <a href="{% url 'accounts:single_station' station.id %}" class="shadow-lg rounded-lg px-4 py-2 w-5/6">
                  <div class="flex justify-between">
                    <img src="/static/images/climatology.png" class="w-10 h-10" alt="">
                    <div>
                        <h2 class="font-bold text-lg">{{station.station_name}}</h2>
                        <p class="text-gray-700">{{station.district}}</p>
                        <p class="text-gray-700">{{station.station_number}}</p>
                    </div>
                  </div>
                  <div class="mt-4">

                    {% if station.station.name == Null %}
                    <p class="text-gray-700 text-sm">No Observer assigned at the moment</p>
                    {% else %}
                    <p>{{station.station.name}} -  Observer</p>
                    {% endif %}
                  </div>
                </a>
           {% endfor %}
           </div>
        </div>
        {% else %}
        <div class="mt-8">
            <div >
                <div class="grid grid-cols-1 place-items-center justify-center">
                    <a  class="bg-white-500 shadow-lg rounded-lg px-12 py-8 flex mt-8">
                        <i class="fa-solid fa-plus mr-2 text-xl text-gray-700"></i>
                        <p class="text-md text-gray-700">Add New Station </p>
                       </a>
                </div>
            </div>
        </div>
        {% endif %}
    </div>

</div>
{% endblock %}

templates/dashboard/synops.html
{% extends 'base.html' %}
{% block content %}
<div class="p-8">
    <h1 class="font-bold text-gray-800 text-2xl">Synops</h1>
    <div class="mt-8">
        {% if synops %}
        <div class="grid grid-cols-3 gap-4 place-items-center">
            {% for synop in synops %}
            <a class="shadow-lg rounded-lg px-4 py-2">
                <p>{{synop.data.station_id}}</p>
                <div class="mt-2">
                    <p class="text-gray-700">{{synop}}</p>
                </div>
            </a>
            {% endfor %}            
        </div>
        {% else %}
        <div class="mt-8">   
            <p class="text-center">No Synops Available</p>
        </div>
        {% endif %}
    </div>

</div>
{% endblock %}